# -*- coding: utf-8 -*-
"""major_project_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FG2OQFEj7m_NuDA4OUY2v07VANFisnd
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

# Define the base URL and parameters
base_url = "https://www.airlinequality.com/airline-reviews/british-airways"
pages = 10  # Adjust the number of pages as needed
page_size = 100

reviews = []

for i in range(1, pages + 1):
    print(f"Scraping page {i}")

    # Construct the URL for the current page
    url = f"{base_url}/page/{i}/?sortby=post_date%3ADesc&pagesize={page_size}"

    # Fetch the content of the page
    response = requests.get(url)

    # Parse the HTML content
    content = response.content
    parsed_content = BeautifulSoup(content, 'html.parser')

    # Extract reviews
    for para in parsed_content.find_all("div", {"class": "text_content"}):
        reviews.append(para.get_text().strip())

    print(f"   ---> {len(reviews)} total reviews")

# Save reviews to a DataFrame
df = pd.DataFrame({"reviews": reviews})
df.to_csv("BA_reviews.csv", index=False)
print("Reviews saved to BA_reviews.csv")

import re

# Load the data
df = pd.read_csv("BA_reviews.csv")

# Remove unnecessary text
def clean_review(text):
    text = re.sub(r"✅ Trip Verified |", "", text)
    text = re.sub(r"Not Verified |", "", text)
    return text.strip()

df['cleaned_reviews'] = df['reviews'].apply(clean_review)
df.to_csv("cleaned_BA_reviews.csv", index=False)
print("Cleaned reviews saved to cleaned_BA_reviews.csv")

from textblob import TextBlob

# Function to get sentiment
def get_sentiment(text):
    analysis = TextBlob(text)
    return analysis.sentiment.polarity

df['sentiment'] = df['cleaned_reviews'].apply(get_sentiment)
df.to_csv("sentiment_BA_reviews.csv", index=False)
print("Sentiment analysis saved to sentiment_BA_reviews.csv")

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Join all reviews
all_reviews = " ".join(review for review in df['cleaned_reviews'])

# Create a word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_reviews)

# Display the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.savefig("wordcloud_BA_reviews.png")
plt.show()
print("Word cloud saved to wordcloud_BA_reviews.png")

import matplotlib.pyplot as plt

# Sentiment distribution
plt.figure(figsize=(10, 5))
df['sentiment'].hist(bins=20)
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Frequency')
plt.savefig("sentiment_distribution.png")
plt.show()
print("Sentiment distribution saved to sentiment_distribution.png")

